// Mapa imgKey -> ruta de imagen bajo /tree/, vendorizado desde el sub-proyecto
// del árbol tecnológico (aoe2-codex/web/public/tree; desde el Update 185872 los
// íconos salen de nodes.js / upstream_nodes.js, ya no hay img_map.js).
// Lo usa el grafo de counters para mostrar el ícono de cada unidad/línea.
// Se omiten las uniquetech por-civ (todas mapean a los dos íconos genéricos).
export const IMG_MAP: Record<string, string> = {
  // Buildings
  barracks: "img/Building/2.png",
  archery: "img/Building/0.png",
  stable: "img/Building/23.png",
  siege: "img/Building/22.png",
  blacksmith: "img/Building/4.png",
  dock: "img/Building/13.png",
  university: "img/Building/33.png",
  monastery: "img/Building/10.png",
  castle: "img/Building/7.png",
  market: "img/Building/16.png",
  tc: "img/Building/28.png",
  wonder: "img/Building/37.png",

  // Infantería
  militia: "img/Unit/8.png",
  manatarms: "img/Unit/10.png",
  longsword: "img/Unit/13.png",
  twohanded: "img/Unit/12.png",
  champion: "img/Unit/72.png",
  spearman: "img/Unit/31.png",
  pikeman: "img/Unit/11.png",
  halberdier: "img/Unit/104.png",
  eaglescout: "img/Unit/109.png",
  eaglewarrior: "img/Unit/148.png",
  eliteeagle: "img/Unit/149.png",
  champiscout: "img/Unit/540.png",
  champirunner: "img/Unit/555.png",
  champiwarrior: "img/Unit/541.png",
  elitechampi: "img/Unit/542.png",
  legionary: "img/Unit/139.png",
  fire_lancer: "img/Unit/457.png",
  elite_fire_lancer: "img/Unit/458.png",
  flemish_militia: "img/Unit/354.png",
  jian_swordsman: "img/Unit/437.png",
  liao_dao: "img/Unit/463.png",
  white_feather: "img/Unit/434.png",
  temple_guard: "img/Unit/553.png",
  ibirapema: "img/Unit/551.png",
  huskarl_b: "img/Unit/50.png",
  condottiero: "img/Unit/134.png",

  // Archery
  archer: "img/Unit/17.png",
  crossbow: "img/Unit/18.png",
  arbalester: "img/Unit/90.png",
  skirmisher: "img/Unit/20.png",
  eliteskirm: "img/Unit/21.png",
  handcannon: "img/Unit/22.png",
  cavarcher: "img/Unit/19.png",
  hcavarcher: "img/Unit/71.png",
  imp_skirmisher: "img/Unit/229.png",
  elephant_archer: "img/Unit/393.png",
  elite_elephant_archer: "img/Unit/93.png",
  grenadier: "img/Unit/462.png",
  xianbei_raider: "img/Unit/433.png",
  bolas_rider: "img/Unit/547.png",
  elite_bolas_rider: "img/Unit/548.png",
  slinger: "img/Unit/143.png",
  genitour: "img/Unit/201.png",

  // Stable
  scout: "img/Unit/64.png",
  lightcav: "img/Unit/91.png",
  hussar: "img/Unit/103.png",
  knight: "img/Unit/1.png",
  cavalier: "img/Unit/49.png",
  paladin: "img/Unit/2.png",
  camel: "img/Unit/78.png",
  heavycamel: "img/Unit/79.png",
  battleeleph: "img/Unit/228.png",
  eliteeleph: "img/Unit/246.png",
  winged_hussar: "img/Unit/371.png",
  savar: "img/Unit/410.png",
  camel_scout: "img/Unit/392.png",
  imp_camel: "img/Unit/185.png",
  steppe_lancer: "img/Unit/273.png",
  elite_steppe_lancer: "img/Unit/274.png",
  shrivamsha: "img/Unit/391.png",
  elite_shrivamsha: "img/Unit/519.png",
  hei_guang: "img/Unit/429.png",
  heavy_hei_guang: "img/Unit/430.png",
  tarkan_s: "img/Unit/105.png",

  // Siege
  batteringram: "img/Unit/74.png",
  cappedram: "img/Unit/63.png",
  siegeram: "img/Unit/73.png",
  mangonel: "img/Unit/27.png",
  onager: "img/Unit/101.png",
  siegeonager: "img/Unit/102.png",
  scorpion: "img/Unit/80.png",
  heavyscorpion: "img/Unit/89.png",
  bombcannon: "img/Unit/30.png",
  siegetower: "img/Unit/212.png",
  houfnice: "img/Unit/372.png",
  rocket_cart: "img/Unit/459.png",
  heavy_rocket_cart: "img/Unit/460.png",
  flaming_camel: "img/Unit/270.png",
  armored_elephant: "img/Unit/394.png",
  siege_elephant: "img/Unit/395.png",
  mounted_treb: "img/Unit/464.png",
  war_chariot_s: "img/Unit/435.png",
  traction_treb: "img/Unit/428.png",

  // Dock
  fishingship: "img/Unit/24.png",
  transportship: "img/Unit/95.png",
  tradecog: "img/Unit/23.png",
  galley: "img/Unit/87.png",
  wargalley: "img/Unit/25.png",
  galleon: "img/Unit/60.png",
  firegalley: "img/Unit/203.png",
  fireship: "img/Unit/86.png",
  fastfireship: "img/Unit/85.png",
  demoraft: "img/Unit/202.png",
  demoship: "img/Unit/84.png",
  heavydemo: "img/Unit/83.png",
  cannongalleon: "img/Unit/55.png",
  elitecannon: "img/Unit/298.png",
  dragon_ship: "img/Unit/178.png",
  hulk: "img/Unit/566.png",
  war_hulk: "img/Unit/565.png",
  carrack: "img/Unit/567.png",
  dromon: "img/Unit/406.png",
  lou_chuan: "img/Unit/431.png",
  thirisadai: "img/Unit/387.png",
  catapult_gall: "img/Unit/591.png",
  turtle_ship: "img/Unit/116.png",
  longboat: "img/Unit/40.png", // renombrado a longship en el Update 185872
  longship: "img/Unit/40.png",
  elite_longship: "img/Unit/474.png",

  // Regionales nórdicas (Update 185872, The Viking Sagas)
  mounted_crossbow: "img/Unit/900.png",
  heavy_mounted_crossbow: "img/Unit/901.png",
  varangian_guard: "img/Unit/902.png",
  elite_varangian_guard: "img/Unit/903.png",
  caravel_d: "img/Unit/198.png",

  // Monastery
  monk: "img/Unit/292.png",
  warrior_priest: "img/Unit/409.png",
  missionary: "img/Unit/107.png",

  // Castle
  trebuchet: "img/Unit/29.png",
  petard: "img/Unit/113.png",
  kipchak_c: "img/Unit/508.png",
  uniquetech1: "img/Tech/33.png",
  uniquetech2: "img/Tech/107.png",

  // Market / TC / eco
  tradecart: "img/Unit/34.png",
  villager: "img/Unit/15.png",
};
